[package]
name = "collision2d"
version = "0.1.0"
authors = ["Tyler Morton <tbmorton@ucsc.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
ndarray = "0.15.6"
rand = "0.8.5"
