name: Test

on:
  push:
    branches:
      - main

jobs:

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Format Rust code
        run: cargo fmt --all -- --check

  cargo:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout sources
          uses: actions/checkout@v2

      - name: Build Rust code
        run: cargo build

      - name: Test Rust code
        run: cargo test
