name: Test


on:
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Format Rust code
        run: cargo fmt --all -- --check

cargo:
  runs-on: ubuntu-latest
  steps:
    - name: Build Rust code
      run: cargo build

    - name: Test Rust code
      run: cargo test
